CREATE TABLE pokemon_evolution (
    id INT NOT NULL,
    evolved_species_id INT NOT NULL,
    evolution_trigger_id INT NOT NULL,
    trigger_item_id INT,
    minimum_level INT,
    gender_id INT,
    location_id INT,
    held_item_id INT,
    time_of_day VARCHAR(5) CHARACTER SET utf8,
    known_move_id INT,
    known_move_type_id INT,
    minimum_happiness INT,
    minimum_beauty INT,
    minimum_affection INT,
    relative_physical_stats INT,
    party_species_id INT,
    party_type_id INT,
    trade_species_id INT,
    needs_overworld_rain INT,
    turn_upside_down INT,
    PRIMARY KEY (id)
);

INSERT INTO pokemon_evolution VALUES (1,2,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (2,3,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (3,5,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (4,6,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (5,8,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (6,9,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (7,11,1,NULL,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (8,12,1,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (9,14,1,NULL,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (10,15,1,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (11,17,1,NULL,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (12,18,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (13,20,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (14,22,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (15,24,1,NULL,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (16,25,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (17,26,3,83,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (18,28,1,NULL,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (19,30,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (20,31,3,81,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (21,33,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (22,34,3,81,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (23,35,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (24,36,3,81,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (25,38,3,82,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (26,39,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (27,40,3,81,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (28,42,1,NULL,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (29,44,1,NULL,21,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (30,45,3,85,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (31,47,1,NULL,24,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (32,49,1,NULL,31,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (33,51,1,NULL,26,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (34,53,1,NULL,28,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (35,55,1,NULL,33,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (36,57,1,NULL,28,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (37,59,3,82,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (38,61,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (39,62,3,84,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (40,64,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (41,65,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (42,67,1,NULL,28,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (43,68,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (44,70,1,NULL,21,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (45,71,3,85,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (46,73,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (47,75,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (48,76,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (49,78,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (50,80,1,NULL,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (51,82,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (52,85,1,NULL,31,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (53,87,1,NULL,34,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (54,89,1,NULL,38,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (55,91,3,84,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (56,93,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (57,94,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (58,97,1,NULL,26,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (59,99,1,NULL,28,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (60,101,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (61,103,3,85,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (62,105,1,NULL,28,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (63,106,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (64,107,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,-1,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (65,110,1,NULL,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (66,112,1,NULL,42,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (67,113,1,NULL,NULL,NULL,NULL,110,'day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (68,117,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (69,119,1,NULL,33,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (70,121,3,84,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (71,122,1,NULL,NULL,NULL,NULL,NULL,NULL,102,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (72,124,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (73,125,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (74,126,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (75,130,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (76,134,3,84,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (77,135,3,83,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (78,136,3,82,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (79,139,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (80,141,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (81,143,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (82,148,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (83,149,1,NULL,55,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (84,153,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (85,154,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (86,156,1,NULL,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (87,157,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (88,159,1,NULL,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (89,160,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (90,162,1,NULL,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (91,164,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (92,166,1,NULL,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (93,168,1,NULL,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (94,169,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (95,171,1,NULL,27,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (96,176,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (97,178,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (98,180,1,NULL,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (99,181,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (100,182,3,80,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (101,183,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (102,184,1,NULL,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (103,185,1,NULL,NULL,NULL,NULL,NULL,NULL,102,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (104,186,2,NULL,NULL,NULL,NULL,198,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (105,188,1,NULL,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (106,189,1,NULL,27,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (107,192,3,80,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (108,195,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (109,196,1,NULL,NULL,NULL,NULL,NULL,'day',NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (110,197,1,NULL,NULL,NULL,NULL,NULL,'night',NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (111,199,2,NULL,NULL,NULL,NULL,198,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (112,202,1,NULL,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (113,205,1,NULL,31,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (114,208,2,NULL,NULL,NULL,NULL,210,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (115,210,1,NULL,23,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (116,212,2,NULL,NULL,NULL,NULL,210,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (117,217,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (118,219,1,NULL,38,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (119,221,1,NULL,33,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (120,224,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (121,226,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,223,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (122,229,1,NULL,24,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (123,230,2,NULL,NULL,NULL,NULL,212,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (124,232,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (125,233,2,NULL,NULL,NULL,NULL,229,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (126,237,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (127,242,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (128,247,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (129,248,1,NULL,55,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (130,253,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (131,254,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (132,256,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (133,257,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (134,259,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (135,260,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (136,262,1,NULL,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (137,264,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (138,266,1,NULL,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (139,267,1,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (140,268,1,NULL,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (141,269,1,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (142,271,1,NULL,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (143,272,3,84,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (144,274,1,NULL,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (145,275,3,85,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (146,277,1,NULL,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (147,279,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (148,281,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (149,282,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (150,284,1,NULL,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (151,286,1,NULL,23,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (152,288,1,NULL,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (153,289,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (154,291,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (155,292,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (156,294,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (157,295,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (158,297,1,NULL,24,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (159,301,3,81,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (160,305,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (161,306,1,NULL,42,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (162,308,1,NULL,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (163,310,1,NULL,26,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (164,315,1,NULL,NULL,NULL,NULL,NULL,'day',NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (165,317,1,NULL,26,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (166,319,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (167,321,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (168,323,1,NULL,33,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (169,326,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (170,329,1,NULL,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (171,330,1,NULL,45,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (172,332,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (173,334,1,NULL,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (174,340,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (175,342,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (176,344,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (177,346,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (178,348,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (179,350,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,171,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (180,354,1,NULL,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (181,356,1,NULL,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (182,358,1,NULL,NULL,NULL,NULL,NULL,'night',NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (183,362,1,NULL,42,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (184,364,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (185,365,1,NULL,44,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (186,367,2,NULL,NULL,NULL,NULL,203,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (187,368,2,NULL,NULL,NULL,NULL,204,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (188,372,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (189,373,1,NULL,50,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (190,375,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (191,376,1,NULL,45,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (192,388,1,NULL,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (193,389,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (194,391,1,NULL,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (195,392,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (196,394,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (197,395,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (198,397,1,NULL,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (199,398,1,NULL,34,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (200,400,1,NULL,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (201,402,1,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (202,404,1,NULL,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (203,405,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (204,407,3,107,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (205,409,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (206,411,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (207,413,1,NULL,20,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (208,414,1,NULL,20,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (209,416,1,NULL,21,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (210,419,1,NULL,26,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (211,421,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (212,423,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (213,424,1,NULL,NULL,NULL,NULL,NULL,NULL,458,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (214,426,1,NULL,28,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (215,428,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (216,429,3,108,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (217,430,3,108,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (218,432,1,NULL,38,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (219,435,1,NULL,34,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (220,437,1,NULL,33,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (221,444,1,NULL,24,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (222,445,1,NULL,48,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (223,448,1,NULL,NULL,NULL,NULL,NULL,'day',NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (224,450,1,NULL,34,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (225,452,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (226,454,1,NULL,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (227,457,1,NULL,31,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (228,460,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (229,461,1,NULL,NULL,NULL,NULL,303,'night',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (230,462,1,NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (231,463,1,NULL,NULL,NULL,NULL,NULL,NULL,205,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (232,464,2,NULL,NULL,NULL,NULL,298,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (233,465,1,NULL,NULL,NULL,NULL,NULL,NULL,246,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (234,466,2,NULL,NULL,NULL,NULL,299,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (235,467,2,NULL,NULL,NULL,NULL,300,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (236,468,3,107,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (237,469,1,NULL,NULL,NULL,NULL,NULL,NULL,246,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (238,470,1,NULL,NULL,NULL,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (239,471,1,NULL,NULL,NULL,48,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (240,472,1,NULL,NULL,NULL,NULL,304,'night',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (241,473,1,NULL,NULL,NULL,NULL,NULL,NULL,246,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (242,474,2,NULL,NULL,NULL,NULL,301,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (243,475,3,109,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (244,476,1,NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (245,477,2,NULL,NULL,NULL,NULL,302,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (246,478,3,109,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (247,496,1,NULL,17,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (248,497,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (249,499,1,NULL,17,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (250,500,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (251,502,1,NULL,17,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (252,503,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (253,505,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (254,507,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (255,508,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (256,510,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (257,512,3,85,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (258,514,3,82,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (259,516,3,84,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (260,518,3,81,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (261,520,1,NULL,21,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (262,521,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (263,523,1,NULL,27,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (264,525,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (265,526,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (266,528,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (267,530,1,NULL,31,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (268,533,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (269,534,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (270,536,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (271,537,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (272,541,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (273,542,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (274,544,1,NULL,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (275,545,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (276,547,3,80,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (277,549,3,80,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (278,552,1,NULL,29,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (279,553,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (280,555,1,NULL,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (281,558,1,NULL,34,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (282,560,1,NULL,39,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (283,563,1,NULL,34,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (284,565,1,NULL,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (285,567,1,NULL,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (286,569,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (287,571,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (288,573,3,107,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (289,575,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (290,576,1,NULL,41,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (291,578,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (292,579,1,NULL,41,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (293,581,1,NULL,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (294,583,1,NULL,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (295,584,1,NULL,47,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (296,586,1,NULL,34,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (297,589,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,616,0,0);

INSERT INTO pokemon_evolution VALUES (298,591,1,NULL,39,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (299,593,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (300,596,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (301,598,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (302,600,1,NULL,38,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (303,601,1,NULL,49,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (304,603,1,NULL,39,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (305,604,3,83,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (306,606,1,NULL,42,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (307,608,1,NULL,41,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (308,609,3,108,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (309,611,1,NULL,38,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (310,612,1,NULL,48,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (311,614,1,NULL,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (312,617,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,588,0,0);

INSERT INTO pokemon_evolution VALUES (313,620,1,NULL,50,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (314,623,1,NULL,43,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (315,625,1,NULL,52,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (316,628,1,NULL,54,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (317,630,1,NULL,54,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (318,634,1,NULL,50,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (319,635,1,NULL,64,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (320,637,1,NULL,59,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (321,350,2,NULL,NULL,NULL,NULL,580,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (322,462,1,NULL,NULL,NULL,379,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (323,476,1,NULL,NULL,NULL,379,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (324,470,1,NULL,NULL,NULL,375,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (325,471,1,NULL,NULL,NULL,380,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (327,683,2,NULL,NULL,NULL,NULL,687,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (328,662,1,NULL,17,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (329,709,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (330,663,1,NULL,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (331,654,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (332,687,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1);

INSERT INTO pokemon_evolution VALUES (333,655,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (334,651,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (335,693,1,NULL,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (336,652,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (337,657,1,NULL,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (338,658,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (339,680,1,NULL,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (340,705,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (341,666,1,NULL,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (342,665,1,NULL,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (343,689,1,NULL,39,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (344,711,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (345,660,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (346,670,1,NULL,19,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (347,671,3,107,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (348,681,3,108,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (349,675,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,17,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (350,685,2,NULL,NULL,NULL,NULL,686,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (351,691,1,NULL,48,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (352,697,1,NULL,39,NULL,NULL,NULL,'day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (353,699,1,NULL,39,NULL,NULL,NULL,'night',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (354,713,1,NULL,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (355,695,3,80,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (356,668,1,NULL,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (357,673,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (358,706,1,NULL,50,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,0);

INSERT INTO pokemon_evolution VALUES (359,715,1,NULL,48,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (360,678,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (361,700,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,18,NULL,NULL,2,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (362,462,1,NULL,NULL,NULL,629,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (363,470,1,NULL,NULL,NULL,650,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (364,471,1,NULL,NULL,NULL,640,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

INSERT INTO pokemon_evolution VALUES (365,476,1,NULL,NULL,NULL,629,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);

